import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Sidebar & Navigation
    'nav.dashboard': 'Início',
    'nav.products': 'Produtos',
    'nav.sales': 'Vendas',
    'nav.customers': 'Clientes',
    'nav.reports': 'Relatórios',
    'nav.intelligence': 'Inteligência IA',
    'nav.assistant': 'Assistente Virtual',
    'nav.settings': 'Configurações',
    
    // AI Intelligence
    'intelligence.title': 'Funcionalidades Inteligentes',
    'intelligence.subtitle': 'Conheça o poder da IA do MeuCaixa no seu financeiro.',
    'intelligence.recurrence': 'Detecção de Recorrência',
    'intelligence.recurrence_desc': 'Identifica gastos fixos e mensais automaticamente.',
    'intelligence.installments': 'Gestão de Parcelamentos',
    'intelligence.installments_desc': 'Extrai parcelas e valores individuais de compras parceladas.',
    'intelligence.location': 'Mapeamento de Locais',
    'intelligence.location_desc': 'Identifica onde você gasta mais (iFood, Postos, Mercados).',
    'intelligence.intent': 'Análise de Intenção',
    'intelligence.intent_desc': 'Entende se você quer registrar, consultar ou corrigir dados.',
    'intelligence.emotion': 'Sentimento Financeiro',
    'intelligence.emotion_desc': 'Analisa sua relação emocional com o dinheiro em cada mensagem.',
    'intelligence.personalized_for': 'Personalizado para {name}',
    'intelligence.recommendation': 'Recomendação da IA',
    'intelligence.view_details': 'Ver Detalhes',
    'intelligence.back': 'Voltar para Inteligência',
    'intelligence.generate_report': 'Gerar Relatório PDF',
    'intelligence.active_system': 'Sistema Ativo',
    'intelligence.gemini_engine': 'Motor Gemini 3.1',
    'intelligence.analyses_count': '+{count} análises',
    'intelligence.how_it_works': 'Como funciona?',
    'intelligence.step1_title': 'Envie uma Mensagem',
    'intelligence.step1_desc': 'Fale naturalmente no chat ou WhatsApp: "Paguei 50 de luz no mercado hoje".',
    'intelligence.step2_title': 'Processamento Instantâneo',
    'intelligence.step2_desc': 'A IA identifica o item, valor, local, se é parcelado e até como você se sente.',
    'intelligence.step3_title': 'Gestão Automática',
    'intelligence.step3_desc': 'Os dados são salvos e alimentam seus relatórios estratégicos sem você digitar nada.',
    'intelligence.extraction_example': 'Exemplo de Extração',
    'intelligence.extraction_text': '"Comprei um jogo de pneus em 4x de 200 reais na Oficina do João, muito caro!"',
    'intelligence.item': 'Item',
    'intelligence.installments_label': 'Parcelas',
    'intelligence.location_label': 'Local',
    'intelligence.emotion_label': 'Emoção',
    'nav.logout': 'Sair',
    
    // Dashboard
    'dashboard.title': 'Painel de Controle',
    'dashboard.revenue': 'Receita Total',
    'dashboard.expenses': 'Despesas Totais',
    'dashboard.balance': 'Saldo Atual',
    'dashboard.recent_transactions': 'Transações Recentes',
    'dashboard.no_transactions': 'Nenhuma transação encontrada.',
    'dashboard.view_all': 'Ver Tudo',
    'dashboard.expense_distribution': 'Distribuição de Despesas',
    'dashboard.revenue_niches': 'Nichos de Receita',
    'dashboard.ai_insights': 'Insights da IA Empresarial',
    'dashboard.view_strategic': 'Ver Relatório Estratégico',
    'dashboard.view_strategic_report': 'Relatório Estratégico Empresarial',
    'dashboard.products_in_stock': 'Produtos em Estoque',
    'dashboard.active_customers': 'Clientes Ativos',
    'dashboard.insights_title': 'Insights & Sugestões',
    'dashboard.cash_flow_forecast': 'Previsão de Fluxo de Caixa (7 dias)',
    'dashboard.forecast_tooltip': 'Saldo Previsto',
    'dashboard.expense_higher_than_revenue': 'Atenção: Suas despesas estão maiores que suas receitas. Revise seus custos fixos.',
    'dashboard.low_stock_alert': 'Você tem {count} produto(s) com estoque baixo. Considere reabastecer.',
    'dashboard.no_customers_alert': 'Cadastre seus clientes para acompanhar o histórico de vendas e melhorar o relacionamento.',
    'dashboard.healthy_business': 'Seu negócio parece saudável! Continue registrando todas as transações.',
    'dashboard.ai_growth_insight': 'Sua empresa está com um crescimento de 15% em relação ao mês passado. O nicho de "{niche}" é o seu maior gerador de receita. Considere reduzir os gastos em "{expense}" para otimizar o lucro.',
    
    // Products
    'products.title': 'Gestão de Produtos',
    'products.new': 'Novo Produto',
    'products.search': 'Buscar produtos...',
    'products.no_products': 'Nenhum produto cadastrado.',
    'products.name': 'Nome do Produto',
    'products.price': 'Preço de Venda',
    'products.cost': 'Preço de Custo',
    'products.stock': 'Estoque Atual',
    'products.category': 'Categoria',
    'products.save': 'Salvar Produto',
    
    // Sales
    'sales.title': 'Registro de Vendas',
    'sales.new': 'Nova Venda',
    'sales.search': 'Buscar vendas...',
    'sales.no_sales': 'Nenhuma venda registrada.',
    'sales.customer': 'Cliente',
    'sales.product': 'Produto',
    'sales.quantity': 'Quantidade',
    'sales.total': 'Total',
    'sales.date': 'Data',
    
    // Customers (People)
    'customers.title': 'Clientes e Empresas',
    'customers.search': 'Buscar...',
    'customers.type_client': 'Clientes',
    'customers.type_supplier': 'Fornecedores',
    'customers.new_client': 'Novo Cliente',
    'customers.new_supplier': 'Novo Fornecedor',
    'customers.edit_client': 'Editar Cliente',
    'customers.edit_supplier': 'Editar Fornecedor',
    'customers.search_clients': 'Buscar clientes...',
    'customers.search_suppliers': 'Buscar fornecedores...',
    'customers.name_label': 'Nome / Razão Social *',
    'customers.email_label': 'E-mail',
    'customers.phone_label': 'Telefone',
    'customers.document_label': 'CPF / CNPJ',
    'customers.no_customers': 'Nenhum cliente encontrado.',
    'customers.no_suppliers': 'Nenhum fornecedor encontrado.',
    'customers.delete_confirm': 'Tem certeza que deseja excluir este registro?',
    'customers.save_error': 'Erro ao salvar. Verifique as permissões.',
    'customers.delete_error': 'Erro ao excluir.',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificações',
    'settings.appearance': 'Aparência',
    'settings.language': 'Idioma',
    'settings.security': 'Segurança',
    'settings.layout': 'Layout',
    'settings.feedback': 'Enviar Feedback',
    'settings.save': 'Salvar Alterações',
    'settings.theme_light': 'Claro',
    'settings.theme_dark': 'Escuro',
    'settings.theme_auto': 'Ajuste Automático',
    'settings.theme_auto_desc': 'Seguir o tema do sistema operacional',
    'settings.lang_confirm': 'Confirmar Idioma',
    'settings.lang_success': 'Idioma atualizado com sucesso!',
    'settings.upgrade': 'Ver Planos e Assinaturas',
    'settings.profile_photo': 'Foto de Perfil',
    'settings.photo_desc': 'JPG, GIF ou PNG. Max 2MB.',
    'settings.full_name': 'Nome Completo',
    'settings.email': 'E-mail',
    'settings.user_type': 'Tipo de Usuário',
    'settings.admin': 'Administrador',
    'settings.manager': 'Gerente',
    'settings.employee': 'Funcionário',
    'settings.lawyer': 'Advogado',
    'settings.client': 'Cliente',
    'settings.notif_all': 'Ativar todas as notificações',
    'settings.notif_all_desc': 'Receber alertas gerais do sistema.',
    'settings.notif_critical': 'Notificações Críticas',
    'settings.notif_critical_desc': 'Alertas de estoque baixo e falhas.',
    'settings.notif_deadlines': 'Lembretes de Prazos',
    'settings.notif_deadlines_desc': 'Avisos sobre vencimentos e metas.',
    'settings.security_title': 'Segurança',
    'settings.change_password': 'Alterar Senha',
    'settings.current_password': 'Senha atual',
    'settings.new_password': 'Nova senha',
    'settings.update_password': 'Atualizar Senha',
    'settings.biometric': 'Login Biométrico',
    'settings.biometric_desc': 'Usar Face ID / Touch ID',
    'settings.layout_title': 'Ajuste de Layout',
    'settings.static_elements': 'Elementos Estáticos',
    'settings.static_desc': 'Manter menu e chat fixos na tela',
    'settings.feedback_title': 'Enviar Feedback',
    'settings.feedback_placeholder': 'Como podemos melhorar?',
    'settings.send': 'Enviar',
    'team.title': 'Equipe e Permissões',
    'team.subtitle': 'Gerencie quem tem acesso ao seu sistema.',
    'team.new_member': 'Novo Membro',
    'team.email': 'E-mail',
    'team.access_level': 'Nível de Acesso',
    'team.send_invite': 'Enviar Convite',
    'team.invite_success': 'Convite enviado com sucesso!',
    'team.member_removed': 'Membro removido da equipe.',
    'team.status_pending': 'Pendente',
    'team.role_admin': 'Administrador',
    'team.role_manager': 'Gerente',
    'team.role_seller': 'Vendedor',
    
    // Assistant
    'assistant.title': 'Assistente Inteligente',
    'assistant.online': 'Online',
    'assistant.placeholder': 'Como posso ajudar com os planos ou a IA?',
    'assistant.input_placeholder': 'Tire suas dúvidas sobre planos ou IA...',
    'assistant.welcome': 'Olá! Sou seu consultor virtual. Posso te ajudar a entender como nossa IA funciona, tirar dúvidas sobre os planos (Gratuito, Pro e Elite) e te ajudar a escolher o ideal para você. Como posso ajudar?',
    'assistant.registered': 'Registrado: {item} ({currency} {value})',
    'assistant.error_basic': 'O Plano Básico permite apenas o registro de despesas diárias. Faça o upgrade para registrar receitas.',
    
    // Common
    'common.save': 'Salvar',
    'common.new': 'Novo',
    'common.new_client': 'Novo Cliente',
    'common.new_supplier': 'Novo Fornecedor',
    'common.new_customer': 'Novo Cliente',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.back': 'Voltar',
    'common.back_to_plans': 'Voltar para a área de planos',
    'common.finish_setup': 'Concluir Cadastro',
    'profile.title': 'Configuração do Perfil',
    'profile.subtitle': 'Complete os dados da sua empresa para continuar.',
    'profile.company_name': 'Nome da Empresa',
    'profile.company_placeholder': 'Ex: Minha Empresa LTDA',
    'profile.responsible_name': 'Nome do Responsável',
    'profile.responsible_placeholder': 'Nome Completo',
    'profile.cnpj': 'CNPJ da Empresa',
    'profile.about': 'Sobre a Empresa',
    'profile.about_placeholder': 'Fale mais sobre sua empresa (nicho, ramo, etc.)',
    'profile.phone': 'Número de Celular',
    'search.button': 'Buscar (Cmd+K)',
    'search.placeholder': 'Buscar produtos, clientes, transações...',
    'search.no_results': 'Nenhum resultado encontrado para "{query}"',
    'search.type_to_search': 'Digite algo para buscar...',
    'search.products': 'Produtos',
    'search.customers': 'Clientes',
    'search.transactions': 'Transações',
    'search.stock': 'Estoque',
    'report.back': 'Voltar ao Dashboard',
    'report.export': 'Exportar Excel',
    'report.print': 'Imprimir PDF',
    'report.title': 'Relatório Estratégico Empresarial',
    'report.exclusive_elite': 'Esta é uma função exclusiva do Plano Empresarial (Elite). Faça o upgrade para acessar insights estratégicos avançados.',
    'report.performance_analysis': 'Análise de Performance',
    'report.expansion': 'Expansão Estratégica',
    'report.adjustment': 'Ajuste de Rota Necessário',
    'report.growth': 'Crescimento',
    'report.margin': 'Margem Operacional',
    'report.health_score': 'Saúde do Negócio',
    'report.health_desc': 'Baseado em liquidez, margem e crescimento mensal.',
    'report.stock_value': 'Capital Imobilizado (Estoque)',
    'report.swot_title': 'Matriz SWOT Estratégica',
    'report.strengths': 'Forças (Strengths)',
    'report.weaknesses': 'Fraquezas (Weaknesses)',
    'report.opportunities': 'Oportunidades (Opportunities)',
    'report.threats': 'Ameaças (Threats)',
    'report.swot_strength_1': 'Domínio na categoria "{area}".',
    'report.swot_strength_2': 'Fluxo de caixa positivo nos últimos {months} meses.',
    'report.swot_strength_3': 'Baixa dependência de capital externo.',
    'report.swot_weakness_1': 'Concentração excessiva de custos em "{area}".',
    'report.swot_weakness_2': 'Margem operacional comprimida por custos logísticos.',
    'report.swot_weakness_3': 'Falta de diversificação em nichos secundários.',
    'report.swot_opportunity_1': 'Expansão da margem através de automação em "{area}".',
    'report.swot_opportunity_2': 'Aumento de ticket médio no setor de "{area}".',
    'report.swot_opportunity_3': 'Novas parcerias logísticas para reduzir fretes.',
    'report.swot_threat_1': 'Volatilidade de preços em insumos operacionais.',
    'report.swot_threat_2': 'Entrada de novos concorrentes no nicho de "{area}".',
    'report.swot_threat_3': 'Possível desaceleração do consumo no próximo trimestre.',
    'report.resolution_title': 'Tabela de Resolução Estratégica',
    'report.problem': 'Problema Identificado',
    'report.cause': 'Análise de Causa',
    'report.resolution': 'Resolução Proposta',
    'report.priority': 'Prioridade',
    'report.problem_1': 'Dreno em "{area}"',
    'report.cause_1': 'Falta de controle granular e processos manuais.',
    'report.res_1': 'Implementar ERP e auditar fornecedores.',
    'report.problem_2': 'Gargalo Logístico',
    'report.cause_2': 'Dependência de player único e rotas ineficientes.',
    'report.res_2': 'Diversificar transportadoras e usar cross-docking.',
    'report.problem_3': 'Retenção de Clientes',
    'report.cause_3': 'Baixo investimento em pós-venda em "{area}".',
    'report.res_3': 'Criar programa de fidelidade e CRM ativo.',
    'report.priority_critical': 'Crítica',
    'report.priority_high': 'Alta',
    'report.priority_medium': 'Média',
    'report.action_plan': 'Plano de Ação Estratégico',
    'report.30_days': '30 Dias',
    'report.90_days': '90 Dias',
    'report.1_year': '1 Ano',
    'report.action_30_title': 'Saneamento',
    'report.action_30_desc': 'Reduzir em 15% os custos fixos de "{area}" através de renegociação direta.',
    'report.action_90_title': 'Escalabilidade',
    'report.action_90_desc': 'Expandir a operação em "{area}" para novos canais de venda digitais.',
    'report.action_1y_title': 'Consolidação',
    'report.action_1y_desc': 'Alcançar margem líquida de 25% e liderança regional no nicho principal.',
    'report.no_area_critical': 'Nenhuma área crítica identificada',
    'report.no_area_highlight': 'Nenhuma área de destaque identificada',
    'products.subtitle': 'Gerencie seu estoque e catálogo de produtos.',
    'products.edit': 'Editar Produto',
    'products.search_placeholder': "Buscar por nome, categoria, local ou 'baixo'...",
    'products.name_label': 'Nome do Produto',
    'products.price_label': 'Preço ({currency})',
    'products.category_label': 'Categoria',
    'products.stock_label': 'Estoque Atual',
    'products.min_stock_label': 'Estoque Mínimo',
    'products.location_label': 'Local do Estoque (Opcional)',
    'products.location_placeholder': 'Ex: Depósito A, Loja Matriz',
    'products.delete_confirm': 'Tem certeza que deseja excluir este produto?',
    'products.save_error': 'Erro ao salvar produto.',
    'products.low_stock': 'Estoque Baixo',
    'products.table_product': 'Produto',
    'products.table_category': 'Categoria',
    'products.table_location': 'Local',
    'products.table_price': 'Preço',
    'products.table_stock': 'Estoque',
    'sales.available_products': 'Produtos Disponíveis',
    'sales.search_placeholder': 'Buscar produto...',
    'sales.in_stock': '{count} em estoque',
    'sales.add_to_cart': 'Adicionar',
    'sales.no_products': 'Nenhum produto encontrado.',
    'sales.summary_title': 'Resumo da Venda',
    'sales.client_label': 'Cliente (Opcional)',
    'sales.client_placeholder': 'Selecione um cliente...',
    'sales.cart_empty': 'Carrinho vazio',
    'sales.subtotal': 'Subtotal',
    'sales.discount': '% Desconto',
    'sales.tax': '% Imposto',
    'sales.checkout': 'Finalizar Venda',
    'sales.processing': 'Processando...',
    'sales.error_empty_cart': 'Adicione produtos ao carrinho',
    'sales.error_stock': 'Estoque insuficiente',
    'sales.error_no_stock': 'Produto sem estoque',
    'sales.success': 'Venda finalizada com sucesso!',
    'sales.error_checkout': 'Erro ao finalizar venda',
    'auth.login': 'Entrar',
    'auth.welcome_back': 'Bem-vindo de volta!',
    'auth.login_subtitle': 'Acesse sua conta para gerenciar suas finanças.',
    'auth.create_account': 'Crie sua conta',
    'auth.register_subtitle': 'Comece sua jornada financeira inteligente hoje.',
    'auth.register': 'Cadastrar',
    'auth.email_placeholder': 'Seu email',
    'auth.password_placeholder': 'Sua senha',
    'auth.company_name': 'Nome da Empresa',
    'auth.owner_name': 'Nome do Responsável',
    'auth.cnpj': 'CNPJ da Empresa',
    'auth.company_desc': 'Fale mais sobre sua empresa (nicho, ramo, etc.)',
    'auth.phone_label': 'Número de Celular',
    'auth.action_login': 'Entrar na Conta',
    'auth.action_register': 'Criar Minha Conta',
    'auth.or_continue_with': 'Ou continue com',
    'auth.error_invalid': 'Email ou senha incorretos.',
    'auth.error_email_in_use': 'Este email já está em uso. Tente fazer login.',
    'auth.error_weak_password': 'A senha deve ter pelo menos 6 caracteres.',
    'auth.error_not_allowed': 'O cadastro com email/senha não está ativado no Console do Firebase.',
    'auth.error_google_not_allowed': 'O login com Google não está ativado no Console do Firebase.',
    'auth.error_google_failed': 'Falha ao entrar com Google.',
    'auth.forgot_password': 'Esqueceu sua senha?',
    'auth.no_account': 'Não tem uma conta? Cadastre-se',
    'auth.have_account': 'Já tem uma conta? Entre aqui',
    'auth.switch_to_login': 'Mudar para tela de login',
    'auth.remember_me': 'Lembrar de mim',
    'auth.setup_helper_title': 'Ação Necessária no Console',
    'auth.setup_helper_step1': 'Acesse o Painel de Autenticação',
    'auth.setup_helper_step2': 'Clique no botão "Add new provider"',
    'auth.setup_helper_step3': 'Ative as opções E-mail/Senha e Google',
    'auth.setup_helper_step4': 'Certifique-se de clicar em Salvar em cada uma',
    'auth.setup_helper_retry': 'Já ativei, tentar novamente',
    'trial.expired_title': 'Seu teste grátis acabou',
    'trial.expired_desc': 'Assine um dos planos para continuar acessando a IA e todas as ferramentas de gestão do MeuCaixa.',
    'trial.get_plans': 'Adquirir Planos',
    'trial.14_days_free': '14 dias grátis',
    'notifications.title': 'Notificações',
    'notifications.none': 'Nenhuma notificação no momento.',
    'notifications.low_stock': 'Estoque Baixo',
    'notifications.low_stock_desc': '{name} ({count} restantes)',
    'notifications.pending_payment': 'Pagamento Pendente',
    'notifications.overdue_payment': 'Pagamento Atrasado',
    'notifications.sales_goal_title': 'Meta de Vendas Atingida!',
    'notifications.sales_goal_desc': 'Você vendeu mais de R$ 5.000,00 hoje. Parabéns!',
    'common.whatsapp_support': 'Suporte WhatsApp',
    'common.bot_support': 'Suporte IA (Bot)',
    'account.change_data': 'Alterar Dados',
    'account.current_email': 'E-mail Atual',
    'account.new_email': 'Novo E-mail',
    'account.confirm_change': 'Confirmar Alteração',
    'account.update_success': 'Dados de acesso atualizados com sucesso! (Simulação)',
    'tx.status_paid': 'Pago',
    'tx.status_pending': 'Pendente',
    'tx.status_overdue': 'Atrasado',
    'tx.due_date': 'Vence: {date}',
    'tx.action_charge': 'Cobrar',
    'tx.action_mark_paid': 'Marcar Pago',
    'sub.price_free': 'Gratuito',
    'sub.price_pro': 'R$ 29,90',
    'sub.price_elite': 'R$ 99,90',
    'sub.price_monthly': '/mês',
    'sub.upgrade_title': 'Upgrade de Plano',
    'sub.welcome_title': 'Bem-vindo ao MeuCaixa!',
    'sub.upgrade_desc': 'Escolha um plano superior para desbloquear novas funcionalidades estratégicas.',
    'sub.welcome_desc': 'Para começar a organizar suas finanças, escolha o plano que melhor se adapta às suas necessidades.',
    'sub.cancel_upgrade': 'Cancelar Upgrade',
    'sub.plan_free': 'Plano Básico (Teste 14 dias)',
    'sub.plan_pro': 'Pro',
    'sub.plan_elite': 'Elite',
    'sub.free_desc': 'Ideal para começar a organizar seu caixa.',
    'sub.pro_desc': 'IA personalizada e acompanhamento inteligente.',
    'sub.elite_desc': 'Alta performance e evolução acelerada.',
    'sub.feature_limited_access': 'Acesso limitado',
    'sub.feature_basic_functions': 'Funções básicas',
    'sub.feature_no_deep_customization': 'Sem personalização profunda',
    'sub.feature_no_advanced_tracking': 'Sem acompanhamento avançado',
    'sub.feature_custom_ai': 'IA personalizada',
    'sub.feature_full_plans': 'Plano diário, semanal e mensal completo',
    'sub.feature_auto_adjustments': 'Ajustes automáticos baseados no usuário',
    'sub.feature_intelligent_tracking': 'Acompanhamento inteligente',
    'sub.feature_pro_plus': 'Tudo do Plano Pro +',
    'sub.feature_advanced_mode': 'Modo avançado (estratégico e intenso)',
    'sub.feature_exclusive_challenges': 'Desafios exclusivos',
    'sub.feature_high_performance': 'Foco em alta performance',
    'sub.feature_accelerated_evolution': 'Evolução acelerada',
    'sub.feature_custom_dashboard': 'Dashboard Personalizado',
    'sub.feature_priority_support': 'Suporte Prioritário',
    'sub.action_enter': 'Entrar no App',
    'sub.action_choose': 'Escolher Plano',
    'sub.action_buy': 'Adquirir Plano',
    'sub.action_subscribe_pro': 'Assinar Pro',
    'sub.action_talk_consultant': 'Adquirir / Falar com Consultor',
    'sub.talk_consultant': 'Falar com Consultor',
    'sub.consultant_desc': 'Tire suas dúvidas sobre os planos',
    'sub.consultant_title': 'Consultor MeuCaixa',
    'sub.consultant_online': 'Especialista em Planos',
    'sub.consultant_welcome': 'Olá! Sou seu Consultor MeuCaixa. Estou aqui exclusivamente para tirar suas dúvidas sobre nossos planos e ajudar você a escolher a melhor opção para o seu negócio. Como posso te ajudar hoje?',
    'sub.consultant_placeholder': 'Tire sua dúvida sobre os planos...',
    'sub.most_popular': 'Mais Popular',
    'onboarding.skip': 'Pular',
    'onboarding.back': 'Voltar',
    'onboarding.next': 'Próximo',
    'onboarding.start': 'Começar Agora',
    'onboarding.beta_tag': 'Versão Beta Exclusiva',
    'onboarding.step1_title': 'O Futuro da sua Gestão Financeira',
    'onboarding.step1_desc': 'Conheça o MeuCaixa IA, o assistente que transforma mensagens simples em controle financeiro absoluto.',
    'onboarding.step2_title': 'Inteligência que entende você',
    'onboarding.step2_desc': 'Esqueça planilhas chatas. Apenas diga: \'Gastei 50 reais em almoço\' e nossa IA categoriza tudo instantaneamente.',
    'onboarding.step3_title': 'Visualize seu Sucesso',
    'onboarding.step3_desc': 'Gráficos inteligentes e insights personalizados para ajudar você a economizar e investir no que realmente importa.',
    'onboarding.step4_title': 'Pronto para Transformar?',
    'onboarding.step4_desc': 'Junte-se a milhares de usuários que já simplificaram suas vidas financeiras com o MeuCaixa IA.',
  },
  en: {
    // Sidebar & Navigation
    'nav.dashboard': 'Home',
    'nav.products': 'Products',
    'nav.sales': 'Sales',
    'nav.customers': 'Clients',
    'nav.reports': 'Reports',
    'nav.intelligence': 'AI Intelligence',
    'nav.assistant': 'Virtual Assistant',
    'nav.settings': 'Settings',

    // AI Intelligence
    'intelligence.title': 'Intelligent Features',
    'intelligence.subtitle': 'Discover the power of MeuCaixa AI in your finances.',
    'intelligence.recurrence': 'Recurrence Detection',
    'intelligence.recurrence_desc': 'Automatically identifies fixed and monthly expenses.',
    'intelligence.installments': 'Installment Management',
    'intelligence.installments_desc': 'Extracts installments and individual values from purchases.',
    'intelligence.location': 'Location Mapping',
    'intelligence.location_desc': 'Identifies where you spend the most (iFood, Gas Stations, Markets).',
    'intelligence.intent': 'Intent Analysis',
    'intelligence.intent_desc': 'Understands if you want to record, query, or correct data.',
    'intelligence.emotion': 'Financial Sentiment',
    'intelligence.emotion_desc': 'Analyzes your emotional relationship with money in each message.',
    'intelligence.personalized_for': 'Personalized for {name}',
    'intelligence.recommendation': 'AI Recommendation',
    'intelligence.view_details': 'View Details',
    'intelligence.back': 'Back to Intelligence',
    'intelligence.generate_report': 'Generate PDF Report',
    'intelligence.active_system': 'System Active',
    'intelligence.gemini_engine': 'Gemini 3.1 Engine',
    'intelligence.analyses_count': '+{count} analyses',
    'intelligence.how_it_works': 'How it works?',
    'intelligence.step1_title': 'Send a Message',
    'intelligence.step1_desc': 'Speak naturally in chat or WhatsApp: "I paid 50 for electricity at the market today".',
    'intelligence.step2_title': 'Instant Processing',
    'intelligence.step2_desc': 'The AI identifies the item, value, location, if it\'s in installments, and even how you feel.',
    'intelligence.step3_title': 'Automatic Management',
    'intelligence.step3_desc': 'Data is saved and feeds your strategic reports without you typing anything.',
    'intelligence.extraction_example': 'Extraction Example',
    'intelligence.extraction_text': '"I bought a set of tires in 4x of 200 dollars at João\'s Shop, very expensive!"',
    'intelligence.item': 'Item',
    'intelligence.installments_label': 'Installments',
    'intelligence.location_label': 'Location',
    'intelligence.emotion_label': 'Emotion',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.revenue': 'Total Revenue',
    'dashboard.expenses': 'Total Expenses',
    'dashboard.balance': 'Current Balance',
    'dashboard.recent_transactions': 'Recent Transactions',
    'dashboard.no_transactions': 'No transactions found.',
    'dashboard.view_all': 'View All',
    'dashboard.expense_distribution': 'Expense Distribution',
    'dashboard.revenue_niches': 'Revenue Niches',
    'dashboard.ai_insights': 'Business AI Insights',
    'dashboard.view_strategic': 'View Strategic Report',
    'dashboard.view_strategic_report': 'Strategic Business Report',
    'dashboard.products_in_stock': 'Products in Stock',
    'dashboard.active_customers': 'Active Customers',
    'dashboard.insights_title': 'Insights & Suggestions',
    'dashboard.cash_flow_forecast': 'Cash Flow Forecast (7 days)',
    'dashboard.forecast_tooltip': 'Predicted Balance',
    'dashboard.expense_higher_than_revenue': 'Attention: Your expenses are higher than your revenue. Review your fixed costs.',
    'dashboard.low_stock_alert': 'You have {count} product(s) with low stock. Consider restocking.',
    'dashboard.no_customers_alert': 'Register your customers to track sales history and improve relationships.',
    'dashboard.healthy_business': 'Your business looks healthy! Keep recording all transactions.',
    'dashboard.ai_growth_insight': 'Your company has grown by 15% compared to last month. The "{niche}" niche is your biggest revenue generator. Consider reducing spending on "{expense}" to optimize profit.',
    
    // Products
    'products.title': 'Product Management',
    'products.new': 'New Product',
    'products.search': 'Search products...',
    'products.no_products': 'No products registered.',
    'products.name': 'Product Name',
    'products.price': 'Selling Price',
    'products.cost': 'Cost Price',
    'products.stock': 'Current Stock',
    'products.category': 'Category',
    'products.save': 'Save Product',
    
    // Sales
    'sales.title': 'Sales Records',
    'sales.new': 'New Sale',
    'sales.search': 'Search sales...',
    'sales.no_sales': 'No sales recorded.',
    'sales.customer': 'Customer',
    'sales.product': 'Product',
    'sales.quantity': 'Quantity',
    'sales.total': 'Total',
    'sales.date': 'Date',
    
    // Customers (People)
    'customers.title': 'Clients & Companies',
    'customers.search': 'Search...',
    'customers.no_customers': 'No customers found.',
    'customers.no_suppliers': 'No suppliers found.',
    'customers.name': 'Name',
    'customers.email': 'E-mail',
    'customers.phone': 'Phone',
    'customers.document': 'Document',
    'customers.type_client': 'Clients',
    'customers.type_supplier': 'Suppliers',
    'customers.new_client': 'New Client',
    'customers.edit_client': 'Edit Client',
    'customers.edit_supplier': 'Edit Supplier',
    'customers.search_clients': 'Search clients...',
    'customers.search_suppliers': 'Search suppliers...',
    'customers.name_label': 'Name / Company Name *',
    'customers.email_label': 'E-mail',
    'customers.phone_label': 'Phone',
    'customers.document_label': 'CPF / CNPJ',
    'customers.delete_confirm': 'Are you sure you want to delete this record?',
    'customers.save_error': 'Error saving. Check permissions.',
    'customers.delete_error': 'Error deleting.',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.security': 'Security',
    'settings.layout': 'Layout',
    'settings.feedback': 'Send Feedback',
    'settings.save': 'Save Changes',
    'settings.theme_light': 'Light',
    'settings.theme_dark': 'Dark',
    'settings.theme_auto': 'Auto Adjust',
    'settings.theme_auto_desc': 'Follow system theme',
    'settings.lang_confirm': 'Confirm Language',
    'settings.lang_success': 'Language updated successfully!',
    'settings.upgrade': 'View Plans & Subscriptions',
    'settings.profile_photo': 'Profile Photo',
    'settings.photo_desc': 'JPG, GIF, or PNG. Max 2MB.',
    'settings.full_name': 'Full Name',
    'settings.email': 'Email',
    'settings.user_type': 'User Type',
    'settings.admin': 'Administrator',
    'settings.manager': 'Manager',
    'settings.employee': 'Employee',
    'settings.lawyer': 'Lawyer',
    'settings.client': 'Client',
    'settings.notif_all': 'Enable all notifications',
    'settings.notif_all_desc': 'Receive general system alerts.',
    'settings.notif_critical': 'Critical Notifications',
    'settings.notif_critical_desc': 'Low stock and failure alerts.',
    'settings.notif_deadlines': 'Deadline Reminders',
    'settings.notif_deadlines_desc': 'Alerts about expirations and goals.',
    'settings.security_title': 'Security',
    'settings.change_password': 'Change Password',
    'settings.current_password': 'Current password',
    'settings.new_password': 'New password',
    'settings.update_password': 'Update Password',
    'settings.biometric': 'Biometric Login',
    'settings.biometric_desc': 'Use Face ID / Touch ID',
    'settings.layout_title': 'Layout Adjustment',
    'settings.static_elements': 'Static Elements',
    'settings.static_desc': 'Keep menu and chat fixed on screen',
    'settings.feedback_title': 'Send Feedback',
    'settings.feedback_placeholder': 'How can we improve?',
    'settings.send': 'Send',
    'team.title': 'Team & Permissions',
    'team.subtitle': 'Manage who has access to your system.',
    'team.new_member': 'New Member',
    'team.email': 'Email',
    'team.access_level': 'Access Level',
    'team.send_invite': 'Send Invite',
    'team.invite_success': 'Invite sent successfully!',
    'team.member_removed': 'Member removed from team.',
    'team.status_pending': 'Pending',
    'team.role_admin': 'Administrator',
    'team.role_manager': 'Manager',
    'team.role_seller': 'Seller',
    
    // Assistant
    'assistant.title': 'Intelligent Assistant',
    'assistant.online': 'Online',
    'assistant.placeholder': 'How can I help with plans or AI?',
    'assistant.input_placeholder': 'Ask your questions about plans or AI...',
    'assistant.welcome': 'Hello! I am your virtual consultant. I can help you understand how our AI works, answer questions about our plans (Free, Pro, and Elite), and help you choose the ideal one for you. How can I help?',
    'assistant.registered': 'Registered: {item} ({currency} {value})',
    'assistant.error_basic': 'The Basic Plan only allows daily expense recording. Upgrade to record revenue.',
    
    // Common
    'common.save': 'Save',
    'common.new': 'New',
    'common.new_client': 'New Client',
    'common.new_supplier': 'New Supplier',
    'common.new_customer': 'New Client',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.back_to_plans': 'Back to plans area',
    'common.finish_setup': 'Finish Setup',
    'profile.title': 'Profile Setup',
    'profile.subtitle': 'Complete your company data to continue.',
    'profile.company_name': 'Company Name',
    'profile.company_placeholder': 'Ex: My Company LLC',
    'profile.responsible_name': 'Responsible Name',
    'profile.responsible_placeholder': 'Full Name',
    'profile.cnpj': 'Company CNPJ/Tax ID',
    'profile.about': 'About the Company',
    'profile.about_placeholder': 'Tell us more about your company (niche, industry, etc.)',
    'profile.phone': 'Mobile Number',
    'search.button': 'Search (Cmd+K)',
    'search.placeholder': 'Search products, customers, transactions...',
    'search.no_results': 'No results found for "{query}"',
    'search.type_to_search': 'Type something to search...',
    'search.products': 'Products',
    'search.customers': 'Customers',
    'search.transactions': 'Transactions',
    'search.stock': 'Stock',
    'report.back': 'Back to Dashboard',
    'report.export': 'Export Excel',
    'report.print': 'Print PDF',
    'report.title': 'Strategic Business Report',
    'report.exclusive_elite': 'This is an exclusive feature of the Business Plan (Elite). Upgrade to access advanced strategic insights.',
    'report.performance_analysis': 'Performance Analysis',
    'report.expansion': 'Strategic Expansion',
    'report.adjustment': 'Route Adjustment Needed',
    'report.growth': 'Growth',
    'report.margin': 'Operating Margin',
    'report.health_score': 'Business Health',
    'report.health_desc': 'Based on liquidity, margin, and monthly growth.',
    'report.stock_value': 'Fixed Capital (Stock)',
    'report.swot_title': 'Strategic SWOT Matrix',
    'report.strengths': 'Strengths',
    'report.weaknesses': 'Weaknesses',
    'report.opportunities': 'Opportunities',
    'report.threats': 'Threats',
    'report.swot_strength_1': 'Dominance in the "{area}" category.',
    'report.swot_strength_2': 'Positive cash flow in the last {months} months.',
    'report.swot_strength_3': 'Low dependence on external capital.',
    'report.swot_weakness_1': 'Excessive cost concentration in "{area}".',
    'report.swot_weakness_2': 'Operating margin compressed by logistics costs.',
    'report.swot_weakness_3': 'Lack of diversification in secondary niches.',
    'report.swot_opportunity_1': 'Margin expansion through automation in "{area}".',
    'report.swot_opportunity_2': 'Increase in average ticket in the "{area}" sector.',
    'report.swot_opportunity_3': 'New logistics partnerships to reduce freight.',
    'report.swot_threat_1': 'Price volatility in operational inputs.',
    'report.swot_threat_2': 'Entry of new competitors in the "{area}" niche.',
    'report.swot_threat_3': 'Possible consumption slowdown in the next quarter.',
    'report.resolution_title': 'Strategic Resolution Table',
    'report.problem': 'Identified Problem',
    'report.cause': 'Cause Analysis',
    'report.resolution': 'Proposed Resolution',
    'report.priority': 'Priority',
    'report.problem_1': 'Drain in "{area}"',
    'report.cause_1': 'Lack of granular control and manual processes.',
    'report.res_1': 'Implement ERP and audit suppliers.',
    'report.problem_2': 'Logistics Bottleneck',
    'report.cause_2': 'Dependence on a single player and inefficient routes.',
    'report.res_2': 'Diversify carriers and use cross-docking.',
    'report.problem_3': 'Customer Retention',
    'report.cause_3': 'Low investment in after-sales in "{area}".',
    'report.res_3': 'Create loyalty program and active CRM.',
    'report.priority_critical': 'Critical',
    'report.priority_high': 'High',
    'report.priority_medium': 'Medium',
    'report.action_plan': 'Strategic Action Plan',
    'report.30_days': '30 Days',
    'report.90_days': '90 Days',
    'report.1_year': '1 Year',
    'report.action_30_title': 'Sanitation',
    'report.action_30_desc': 'Reduce fixed costs of "{area}" by 15% through direct renegotiation.',
    'report.action_90_title': 'Scalability',
    'report.action_90_desc': 'Expand operation in "{area}" to new digital sales channels.',
    'report.action_1y_title': 'Consolidation',
    'report.action_1y_desc': 'Achieve 25% net margin and regional leadership in the main niche.',
    'report.no_area_critical': 'No critical area identified',
    'report.no_area_highlight': 'No highlight area identified',
    'products.subtitle': 'Manage your stock and product catalog.',
    'products.edit': 'Edit Product',
    'products.search_placeholder': "Search by name, category, location or 'low'...",
    'products.name_label': 'Product Name',
    'products.price_label': 'Price ({currency})',
    'products.category_label': 'Category',
    'products.stock_label': 'Current Stock',
    'products.min_stock_label': 'Minimum Stock',
    'products.location_label': 'Stock Location (Optional)',
    'products.location_placeholder': 'Ex: Warehouse A, Main Store',
    'products.delete_confirm': 'Are you sure you want to delete this product?',
    'products.save_error': 'Error saving product.',
    'products.low_stock': 'Low Stock',
    'products.table_product': 'Product',
    'products.table_category': 'Category',
    'products.table_location': 'Location',
    'products.table_price': 'Price',
    'products.table_stock': 'Stock',
    'sales.available_products': 'Available Products',
    'sales.search_placeholder': 'Search product...',
    'sales.in_stock': '{count} in stock',
    'sales.add_to_cart': 'Add',
    'sales.no_products': 'No products found.',
    'sales.summary_title': 'Sale Summary',
    'sales.client_label': 'Client (Optional)',
    'sales.client_placeholder': 'Select a client...',
    'sales.cart_empty': 'Cart is empty',
    'sales.subtotal': 'Subtotal',
    'sales.discount': '% Discount',
    'sales.tax': '% Tax',
    'sales.checkout': 'Finish Sale',
    'sales.processing': 'Processing...',
    'sales.error_empty_cart': 'Add products to the cart',
    'sales.error_stock': 'Insufficient stock',
    'sales.error_no_stock': 'Product out of stock',
    'sales.success': 'Sale completed successfully!',
    'sales.error_checkout': 'Error completing sale',
    'auth.login': 'Login',
    'auth.welcome_back': 'Welcome back!',
    'auth.login_subtitle': 'Access your account to manage your finances.',
    'auth.create_account': 'Create your account',
    'auth.register_subtitle': 'Start your smart financial journey today.',
    'auth.register': 'Register',
    'auth.email_placeholder': 'Your email',
    'auth.password_placeholder': 'Your password',
    'auth.company_name': 'Company Name',
    'auth.owner_name': 'Owner Name',
    'auth.cnpj': 'Company CNPJ',
    'auth.company_desc': 'Tell us more about your company (niche, industry, etc.)',
    'auth.phone_label': 'Cell Phone Number',
    'auth.action_login': 'Login to Account',
    'auth.action_register': 'Create My Account',
    'auth.or_continue_with': 'Or continue with',
    'auth.error_invalid': 'Incorrect email or password.',
    'auth.error_email_in_use': 'This email is already in use. Try logging in.',
    'auth.error_weak_password': 'Password must be at least 6 characters long.',
    'auth.error_not_allowed': 'Email/password registration is not enabled in the Firebase Console.',
    'auth.error_google_not_allowed': 'Google login is not enabled in the Firebase Console.',
    'auth.error_google_failed': 'Failed to sign in with Google.',
    'auth.forgot_password': 'Forgot your password?',
    'auth.no_account': "Don't have an account? Register",
    'auth.have_account': 'Already have an account? Login',
    'auth.switch_to_login': 'Switch to login screen',
    'auth.remember_me': 'Remember me',
    'auth.setup_helper_title': 'Action Required in Console',
    'auth.setup_helper_step1': 'Access the Authentication Panel',
    'auth.setup_helper_step2': 'Click the "Add new provider" button',
    'auth.setup_helper_step3': 'Enable Email/Password and Google options',
    'auth.setup_helper_step4': 'Make sure to click Save on each one',
    'auth.setup_helper_retry': 'I have enabled it, try again',
    'trial.expired_title': 'Your free trial has ended',
    'trial.expired_desc': 'Subscribe to one of the plans to continue accessing the AI and all MeuCaixa management tools.',
    'trial.get_plans': 'Get Plans',
    'trial.14_days_free': '14 days free',
    'notifications.title': 'Notifications',
    'notifications.none': 'No notifications at the moment.',
    'notifications.low_stock': 'Low Stock',
    'notifications.low_stock_desc': '{name} ({count} remaining)',
    'notifications.pending_payment': 'Pending Payment',
    'notifications.overdue_payment': 'Overdue Payment',
    'notifications.sales_goal_title': 'Sales Goal Reached!',
    'notifications.sales_goal_desc': 'You sold more than $ 5,000.00 today. Congratulations!',
    'common.whatsapp_support': 'WhatsApp Support',
    'common.bot_support': 'AI Support (Bot)',
    'account.change_data': 'Change Data',
    'account.current_email': 'Current Email',
    'account.new_email': 'New Email',
    'account.confirm_change': 'Confirm Change',
    'account.update_success': 'Access data updated successfully! (Simulation)',
    'tx.status_paid': 'Paid',
    'tx.status_pending': 'Pending',
    'tx.status_overdue': 'Overdue',
    'tx.due_date': 'Due: {date}',
    'tx.action_charge': 'Charge',
    'tx.action_mark_paid': 'Mark Paid',
    'sub.upgrade_title': 'Plan Upgrade',
    'sub.welcome_title': 'Welcome to MeuCaixa!',
    'sub.upgrade_desc': 'Choose a higher plan to unlock new strategic features.',
    'sub.welcome_desc': 'To start organizing your finances, choose the plan that best fits your needs.',
    'sub.cancel_upgrade': 'Cancel Upgrade',
    'sub.plan_free': 'Basic Plan (14-day Trial)',
    'sub.plan_pro': 'Pro',
    'sub.plan_elite': 'Elite',
    'sub.free_desc': 'Ideal for starting to organize your cash flow.',
    'sub.pro_desc': 'Custom AI and intelligent tracking.',
    'sub.elite_desc': 'High performance and accelerated evolution.',
    'sub.price_free': 'Free',
    'sub.price_pro': '$ 29.90',
    'sub.price_elite': '$ 99.90',
    'sub.price_monthly': '/month',
    'sub.feature_limited_access': 'Limited access',
    'sub.feature_basic_functions': 'Basic functions',
    'sub.feature_no_deep_customization': 'No deep customization',
    'sub.feature_no_advanced_tracking': 'No advanced tracking',
    'sub.feature_custom_ai': 'Custom AI',
    'sub.feature_full_plans': 'Full daily, weekly, and monthly plans',
    'sub.feature_auto_adjustments': 'Auto-adjustments based on user',
    'sub.feature_intelligent_tracking': 'Intelligent tracking',
    'sub.feature_pro_plus': 'Everything in Pro +',
    'sub.feature_advanced_mode': 'Advanced mode (strategic and intense)',
    'sub.feature_exclusive_challenges': 'Exclusive challenges',
    'sub.feature_high_performance': 'Focus on high performance',
    'sub.feature_accelerated_evolution': 'Accelerated evolution',
    'sub.feature_custom_dashboard': 'Custom Dashboard',
    'sub.feature_priority_support': 'Priority Support',
    'sub.action_enter': 'Enter App',
    'sub.action_choose': 'Choose Plan',
    'sub.action_buy': 'Get Plan',
    'sub.action_subscribe_pro': 'Subscribe Pro',
    'sub.action_talk_consultant': 'Get / Talk to Consultant',
    'sub.talk_consultant': 'Talk to Consultant',
    'sub.consultant_desc': 'Ask your questions about plans',
    'sub.consultant_title': 'MeuCaixa Consultant',
    'sub.consultant_online': 'Plan Specialist',
    'sub.consultant_welcome': 'Hello! I am your MeuCaixa Consultant. I am here exclusively to answer your questions about our plans and help you choose the best option for your business. How can I help you today?',
    'sub.consultant_placeholder': 'Ask your question about plans...',
    'sub.most_popular': 'Most Popular',
    'onboarding.skip': 'Skip',
    'onboarding.back': 'Back',
    'onboarding.next': 'Next',
    'onboarding.start': 'Start Now',
    'onboarding.beta_tag': 'Exclusive Beta Version',
    'onboarding.step1_title': 'The Future of Your Financial Management',
    'onboarding.step1_desc': 'Meet MeuCaixa AI, the assistant that transforms simple messages into absolute financial control.',
    'onboarding.step2_title': 'Intelligence that understands you',
    'onboarding.step2_desc': 'Forget boring spreadsheets. Just say: \'I spent 50 dollars on lunch\' and our AI categorizes everything instantly.',
    'onboarding.step3_title': 'Visualize Your Success',
    'onboarding.step3_desc': 'Smart charts and personalized insights to help you save and invest in what really matters.',
    'onboarding.step4_title': 'Ready to Transform?',
    'onboarding.step4_desc': 'Join thousands of users who have already simplified their financial lives with MeuCaixa AI.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'pt';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(`{${paramKey}}`, String(value));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
