export const NICHOS_GLOBAIS = [
  "Farmácia",
  "Açougue",
  "Mercado",
  "Restaurante",
  "Oficina mecânica",
  "Salão de beleza",
  "Barbearia",
  "Loja de roupas",
  "E-commerce",
  "Infoprodutor",
  "Agência de marketing",
  "Prestador de serviço",
  "Clínica médica",
  "Dentista",
  "Academia",
  "Transporte",
  "Logística",
  "Construção civil",
  "Tecnologia",
  "Freelancer",
  "Autônomo",
  "Pet Shop",
  "Padaria",
  "Confeitaria",
  "Lanchonete",
  "Cafeteria",
  "Pizzaria",
  "Hortifruti",
  "Loja de Calçados",
  "Loja de Acessórios",
  "Papelaria",
  "Livraria",
  "Floricultura",
  "Joalheria",
  "Ótica",
  "Brinquedos",
  "Artigos Esportivos",
  "Móveis e Decoração",
  "Materiais de Construção",
  "Auto Peças",
  "Posto de Combustível",
  "Hotelaria",
  "Pousada",
  "Turismo",
  "Educação",
  "Escola de Idiomas",
  "Consultoria",
  "Contabilidade",
  "Advocacia",
  "Arquitetura",
  "Engenharia",
  "Design",
  "Fotografia",
  "Eventos",
  "Segurança",
  "Limpeza",
  "Manutenção",
  "Imobiliária",
  "Corretor de Seguros",
  "Artesanato",
  "Moda",
  "Beleza e Estética",
  "Saúde e Bem-estar",
  "Alimentação Saudável",
  "Suplementos",
  "Informática",
  "Desenvolvimento de Software",
  "Marketing Digital",
  "Social Media",
  "Copywriting",
  "Tráfego Pago",
  "Dropshipping",
  "Afiliados",
  "Coach",
  "Mentoria",
  "Palestrante",
  "Escritor",
  "Artista",
  "Músico",
  "Produção Audiovisual",
  "Games",
  "Criptomoedas",
  "Investimentos",
  "Finanças",
  "Religião",
  "ONG",
  "Associação",
  "Clube",
  "Sindicato",
  "Governo",
  "Outro"
];
